# Generated by Django 3.2.8 on 2021-10-27 14:20

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cakesite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='clear_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Нормализованный номер телефона'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='', help_text='+79991234567', max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='social_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка на соцсеть'),
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(max_length=500, null=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(null=True, verbose_name='Дата создания заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_ordered',
            field=models.BooleanField(default=False, verbose_name='Заказ сделан'),
        ),
        migrations.AddField(
            model_name='order',
            name='lettering',
            field=models.TextField(help_text='Мы можем разместить на торте любую надпись, например: «С днем рождения!»', max_length=100, null=True, verbose_name='Надпись'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.CharField(max_length=15, null=True, verbose_name='Промокод'),
        ),
    ]
