# Generated by Django 3.2.8 on 2021-10-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakesite', '0002_auto_20211027_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_time',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата доставки'),
        ),
    ]
