# Generated by Django 3.2.8 on 2021-10-27 16:26

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cakesite', '0003_auto_20211027_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='clear_phone_number',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='+79991234567', max_length=20, region=None, verbose_name='Номер телефона'),
        ),
    ]
