# Generated by Django 3.2.8 on 2021-10-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakesite', '0004_auto_20211027_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ManyToManyField(related_name='product', to='cakesite.Component', verbose_name='Продукт')),
            ],
        ),
    ]
