# Generated by Django 3.2.8 on 2021-10-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakesite', '0005_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукция'},
        ),
        migrations.AlterField(
            model_name='product',
            name='component',
            field=models.ManyToManyField(related_name='product', to='cakesite.Component', verbose_name='Компонент'),
        ),
    ]
