# Generated by Django 3.2.8 on 2021-10-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakesite', '0006_auto_20211027_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='lettering',
        ),
        migrations.AddField(
            model_name='product',
            name='lettering',
            field=models.TextField(help_text='Мы можем разместить на торте любую надпись, например: «С днем рождения!»', max_length=100, null=True, verbose_name='Надпись'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=500, verbose_name='цена'),
        ),
    ]
