# Generated by Django 3.2.8 on 2021-10-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakesite', '0007_auto_20211027_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CK', 'Торт'), ('CC', 'Капкейп'), ('MF', 'Маффин')], default='CK', max_length=2, verbose_name='категория'),
        ),
    ]
