# Generated by Django 3.2.8 on 2021-10-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakesite', '0009_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='order', to='cakesite.Product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CK', 'Торт'), ('CC', 'Капкейк'), ('MF', 'Маффин')], default='CK', max_length=2, verbose_name='категория'),
        ),
    ]
