# Generated by Django 3.2.8 on 2021-10-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakesite', '0010_auto_20211027_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_ordered',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NP', 'Заказ обрабатывается'), ('BN', 'Заказ готовится!'), ('ID', 'Заказ в дороге'), ('CM', 'Заказ завершён!')], default='NP', max_length=2, verbose_name='статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=500, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='promo_code',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Промокод'),
            preserve_default=False,
        ),
    ]
