# Generated by Django 3.2.8 on 2021-10-27 20:01

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cakesite', '0012_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='+79991234567', max_length=20, region=None, verbose_name='Номер телефона'),
        ),
    ]
