# Generated by Django 3.2.8 on 2021-10-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakesite', '0014_alter_order_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NP', 'Заказ обрабатывается'), ('BN', 'Заказ готовится!'), ('ID', 'Заказ в дороге'), ('CM', 'Заказ завершён!'), ('CD', 'Статус отменён!')], default='NP', max_length=2, verbose_name='статус заказа'),
        ),
    ]
